name = input("Enter your name: ")
age = int(input("Enter your age: "))
department = input("Enter your department: ")
salary = float(input("Enter your salary: "))
email = input("Enter your email: ")
phone_number = input("Enter your phone number: ")
YOE = int(input("Enter your year of experience: "))

print("\nEmployee Details:")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"Department: {department}")
print(f"Salary: {salary}")
print(f"Email: {email}")
print(f"Phone Number: {phone_number}")  
print(f"Year of Experience: {YOE}")