name = input("Enter your name: ")
age = int(input("Enter your age: "))
department = input("Enter your department: ")
salary = float(input("Enter your salary: "))

print("\nEmployee Details:")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"Department: {department}")
print(f"Salary: {salary}")